name: schuelerprojekt
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - ipywidgets==7.5.1
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - nbresuse==0.3.3
  - notebook==6.0.3
  - nteract_on_jupyter==2.1.3
  - numpy==1.18.1
  - scipy==1.4.1
  - matplotlib-base==3.1.2
  - jupyterlab==2.0.1
  - nodejs==13.13.0
  - ipympl==0.5.6
  - scikit-image==0.16.2
  - opencv==4.2.0
  - tensorflow==1.15.0
  - cython==0.29.15
  - gitpython==3.1.3
  - pip:
    - rwth-nb==0.1.4
    - python-sofa==0.2.0
